### ISSUE TITLE
java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.freeparking.zack.a_plus_practice/databases/Struggling

### ISSUE THREAD

**Issue by portexe** [Zackazt/CompTIA-Aplus-Study-Practice#8]
The application has been up for two weeks and we've only had a single crash reported.  Here are the full contents of the crash log:

java.lang.IllegalStateException: Could not execute method for android:onClick

```
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
at android.view.View.performClick(View.java:4466)
at android.view.View$PerformClick.run(View.java:18542)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5097)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
```

Caused by: java.lang.reflect.InvocationTargetException

```
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
... 11 more
```

Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/com.freeparking.zack.a_plus_practice/databases/Struggling

```
at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1657)
at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1603)
at com.freeparking.zack.a_plus_practice.PracticeMode.addQuestionToDB(PracticeMode.java:295)
at com.freeparking.zack.a_plus_practice.PracticeMode.onStrugglingButtonClick(PracticeMode.java:269)
```

**Comment by portexe** [comment]
I have figured out what is causing the issue, and have replicated it.  The issue stems from the Android Activity Life-cycle.  

The onStop method is called whenever the activity is no longer visible to the user.  An example would be pressing the home button.  

The onCreate method is called when the activity is started from scratch.  

An example of what could cause the crash:
1. User is on a question.
2. User presses home button.
3. User re-opens app.
4. User adds question to struggling database.
5. App crashes.

I will be fixing this, by calling the createDatabase function using the Android Activity Life-cycle's onStart method.  This method is called whenever the activity becomes visible to the user.
